/*
 * Copyright 2026 IBM Corporation and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.apache.yoko.rmi.util.stub;

import org.apache.yoko.util.concurrent.LazyReference;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

import static java.util.Arrays.asList;
import static java.util.Collections.unmodifiableList;
import static java.util.Collections.unmodifiableMap;
import static java.util.stream.Collectors.joining;

/**
 * Describes the interface of a method to be generated by the stub utility.
 * This class is immutable.
 */
public final class MethodRef {
    private final String name;
    private final Class<?> declaringClass;
    private final Class<?> returnType;
    private final int modifiers;
    private final Method method;
    private final LazyReference<String> signatureRef = new LazyReference<>(this::genSignature);
    private final LazyReference<List<Class<?>>> parameterTypesRef = new LazyReference<>(this::genParameterTypes);
    private final LazyReference<List<Class<?>>> exceptionTypesRef = new LazyReference<>(this::genExceptionTypes);

    public MethodRef(Method method) {
        this.method = method;
        this.name = method.getName();
        this.declaringClass = method.getDeclaringClass();
        this.returnType = method.getReturnType();
        this.modifiers = method.getModifiers();
    }

    static String getKey(Method m) { return m.getName() + getSignature(m.getReturnType(), m.getParameterTypes()); }
    String getKey() { return getName() + getSignature(); }
    public Method getMethod() { return method; }
    public String getName() { return name; }
    public Class<?> getDeclaringClass() { return declaringClass; }
    public List<Class<?>> getParameterTypes() { return parameterTypesRef.get(); }
    private List<Class<?>> genParameterTypes() { return unmodifiableList(asList(method.getParameterTypes())); }
    public Class<?> getReturnType() { return returnType; }
    public List<Class<?>> getExceptionTypes() { return exceptionTypesRef.get(); }
    private List<Class<?>> genExceptionTypes() { return unmodifiableList(asList(method.getExceptionTypes())); }
    public int getModifiers() { return modifiers; }
    public String getSignature() { return signatureRef.get(); }
    private String genSignature() { return getSignature(returnType, method.getParameterTypes()); }

    private static String getSignature(Class<?> rType, Class<?>...pTypes) {
        return Stream.of(pTypes)
                .map(MethodRef::getSignature)
                .collect(joining("", "(", ")" + getSignature(rType)));
    }

    private static final Map<Class<?>, String> KNOWN_TYPE_MAP = unmodifiableMap(
            new HashMap<Class<?>, String>(){{
                put(int.class, "I");
                put(boolean.class, "Z");
                put(byte.class, "B");
                put(short.class, "S");
                put(long.class, "J");
                put(double.class, "D");
                put(float.class, "F");
                put(void.class, "V");
                put(char.class, "C");
            }});

    static String getSignature(Class<?> clz) {
        if (clz.isPrimitive()) return Optional.ofNullable(KNOWN_TYPE_MAP.get(clz))
                .orElseThrow(() -> new InternalError("cannot handle " + clz));
        return clz.isArray() ?
                "[" + getSignature(clz.getComponentType()) :
                "L" + clz.getName().replace('.', '/') + ";";
    }
}
